### ISSUE TITLE
SENDPASS nickname generates a key which is not one-time use

### ISSUE THREAD

**Issue by namoscagnm** [oftc/oftc-ircservices#23] opened 2017-01-04 21:16 UTC
I have just requested /msg nickserv SENDPASS, and got an email with a command to paste in IRC in order to change my password, in the form of "/msg NickServ SENDPASS mynick small-number:big-number <yournewpassword>"

After this, the nickserv had some trouble to recognize me, but eventually it did. Unfortunately, I pasted and sent the message with the big number into the #oftc room because I though this command expires after being used, but to my surprise, people on the channel were able to change my password!

This is very disturbing and I hope I dont lose my nick.

Please, update the system so that this big number becomes invalid after one-time use.
The code for this seems to be inside the file:  oftc-ircservices/modules/nickserv.c

**Comment by namoscagnm** [comment] 2017-01-04 21:42
This type of problem is already predicted to happen 3 years ago: https://github.com/oftc/oftc-ircservices/issues/1

**Comment by Gryllida** [comment] 2017-01-04 21:51
(would like to close this issue and duplicate and continue discussion on the other bug, but I don't see a close button)

**Comment by ChristophBerg** [comment] 2017-01-04 21:59
Duplicate of #1.

**Closed by ChristophBerg** 2017-01-04 21:59 UTC
